[package]
name = "diligent"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
bindgen = "0.71.1"
cmake   = "0.1"

[dependencies]
libc = "0.2.0"

[lib]
name = "diligent"
path = "src/lib.rs"