[package]
name = "diligent"
version = "0.1.0"
edition = "2021"
exclude = ["**/assets"]

description = "A port of the Diligent Engine to Rust"

license-file = "LICENSE.md"

[dependencies]
static_assertions = "1.1.0"
bitflags          = "2.6.0"
libc              = "0.2.0"
xcb               = { version = "1.5.0" , optional = true }
imgui             = "0.12.0"
clap              = { version = "4.5.30", features = ["cargo"] }
glam              = "0.30.0"

[dependencies.diligent_sys]
path = "diligent_sys"

[features]
default = ["VULKAN_SUPPORTED"]
VULKAN_SUPPORTED = ["xcb"]

[lib]
name = "diligent"

[[example]]
name = "Tutorial01_HelloTriangle"
path = "src/samples/tutorials/tutorial01_hello_triangle.rs"

[[example]]
name = "Tutorial02_Cube"
path = "src/samples/tutorials/tutorial02_cube.rs"
